In [ ]:
import numpy as np

In [2]:
mylist=[1,2,3,4]

In [3]:
arr=np.array(mylist)

In [4]:
print(arr)

[1 2 3 4]


In [5]:
arr.shape

(4,)

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr


array([1, 2, 3, 4])

In [13]:
#multidimentional array
a=[1,2,3,4]
b=[6,6,7,8,7]
c=[3,4,5,6]

arr1=np.array([a,b,c])

In [12]:
arr1

array([list([1, 2, 3, 4]), list([6, 6, 7, 8, 7]), list([3, 4, 5, 6])],
      dtype=object)

In [10]:
arr1.shape

(3,)

In [14]:
#multidimentional array
a=[1,2,3,4]
b=[6,6,7,8,7]
c=[3,4,5,6]

arr1=np.array([a,b,c])

In [15]:
arr1


array([list([1, 2, 3, 4]), list([6, 6, 7, 8, 7]), list([3, 4, 5, 6])],
      dtype=object)

In [18]:
mylist1=[1,2,3,4]
mylist2=[3,4,5,6]
mylist3=[7,8,9,0]

arr2=np.array([mylist1,mylist2,mylist3])

In [19]:
arr2


array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [7, 8, 9, 0]])

In [20]:
arr2.shape

(3, 4)

In [22]:
arr2.reshape(4,3)

array([[1, 2, 3],
       [4, 3, 4],
       [5, 6, 7],
       [8, 9, 0]])

In [23]:
arr[3]

4

In [24]:
arr2[1:,3:]

array([[6],
       [0]])

In [25]:
arr2


array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [7, 8, 9, 0]])

In [26]:
arr2[1:,3:]

array([[6],
       [0]])

In [27]:
arr2[:,:]

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [7, 8, 9, 0]])

In [28]:
arr2[0:2,0:2]

array([[1, 2],
       [3, 4]])

In [31]:
arr2[1:,2:]

array([[5, 6],
       [9, 0]])

In [32]:
arr2[1:,1:3]

array([[4, 5],
       [8, 9]])

In [33]:
arr2[1:,0:3]

array([[3, 4, 5],
       [7, 8, 9]])

In [37]:
arr=np.arange(0,10,step=2)

In [38]:
arr

array([0, 2, 4, 6, 8])

In [39]:
np.linspace(1,10,num=50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

#copy function
and broadcasting





In [1]:
arr

NameError: name 'arr' is not defined

In [4]:
arr=np.array[1,2,3,4,5,6,7]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [6]:
arr=np.array([1,2,3,4,5,6,7])

In [7]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
arr[3:]=100

In [9]:
arr

array([  1,   2,   3, 100, 100, 100, 100])

In [10]:
arr1=arr

In [11]:
arr[3:]=500

In [12]:
arr

array([  1,   2,   3, 500, 500, 500, 500])

In [13]:
arr1

array([  1,   2,   3, 500, 500, 500, 500])

In [14]:
arr1=arr.copy()

In [15]:
arr[3:]=1000

In [16]:
arr

array([   1,    2,    3, 1000, 1000, 1000, 1000])

In [17]:
arr1

array([  1,   2,   3, 500, 500, 500, 500])

In [18]:
val=2
arr<2

array([ True, False, False, False, False, False, False])

In [19]:
arr*2

array([   2,    4,    6, 2000, 2000, 2000, 2000])

In [20]:
arr>2

array([False, False,  True,  True,  True,  True,  True])

In [21]:
arr[arr<2]

array([1])

In [22]:
arr[arr>2]

array([   3, 1000, 1000, 1000, 1000])

In [23]:
np.ones(4)

array([1., 1., 1., 1.])

In [25]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [26]:
np.random.rand(3,3)#uniform distributionsd

array([[0.81699569, 0.49211699, 0.14808432],
       [0.22749598, 0.91316988, 0.46166669],
       [0.94235652, 0.94684794, 0.5114039 ]])

In [27]:
np.random.randn(3,3)#normal distributionnp

array([[ 1.36265955, -0.29265667, -0.07682187],
       [-0.93042287,  0.13672347,  0.72842898],
       [-1.30338702,  0.11668428, -1.01116286]])

In [30]:
np.random.randint(0,100,10).reshape(5,2)

array([[24, 87],
       [47,  3],
       [72, 41],
       [91, 29],
       [72, 93]])